apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-alertmanager
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: my-storage-class  # PVC와 일치하는 스토리지 클래스 이름
  hostPath:
    path: /mnt/data/alertmanager  # 클러스터 노드의 적절한 경로로 대체
